import {
  Product,
  Retailer,
  Order,
  Employee,
  Target,
  Delivery,
  Payment,
  ActivityItem,
  ShopVisit,
} from "@/types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    name: "Premium Tea 250g",
    sku: "TEA-250",
    category: "Beverages",
    unit: "Packets",
    mrp: 140,
    retailerPrice: 118,
    warehouseStock: 84,
    reservedStock: 11, // for RF-2026-00482
    lowStockThreshold: 20,
    scheme: "Buy 10, get 1 free",
  },
  {
    id: "prod-2",
    name: "Glucose Biscuit Box",
    sku: "BIS-BOX-24",
    category: "Biscuits & Confectionery",
    unit: "Boxes",
    mrp: 240,
    retailerPrice: 205,
    warehouseStock: 30,
    reservedStock: 8,
    lowStockThreshold: 10,
  },
  {
    id: "prod-3",
    name: "Mustard Oil 1L",
    sku: "OIL-1L",
    category: "Edible Oils",
    unit: "Bottles",
    mrp: 175,
    retailerPrice: 158,
    warehouseStock: 8, // Low stock!
    reservedStock: 4,
    lowStockThreshold: 15,
  },
  {
    id: "prod-4",
    name: "Washing Powder 500g",
    sku: "DET-500",
    category: "Home Care",
    unit: "Packs",
    mrp: 65,
    retailerPrice: 54,
    warehouseStock: 65,
    reservedStock: 0,
    lowStockThreshold: 15,
  },
  {
    id: "prod-5",
    name: "Bath Soap 100g (Pack of 4)",
    sku: "SOAP-4P",
    category: "Personal Care",
    unit: "Packs",
    mrp: 120,
    retailerPrice: 98,
    warehouseStock: 45,
    reservedStock: 0,
    lowStockThreshold: 12,
  },
  {
    id: "prod-6",
    name: "Salt 1kg",
    sku: "SALT-1K",
    category: "Staples & Spices",
    unit: "Packets",
    mrp: 28,
    retailerPrice: 22,
    warehouseStock: 110,
    reservedStock: 0,
    lowStockThreshold: 30,
  },
  {
    id: "prod-7",
    name: "Turmeric Powder 200g",
    sku: "SPICE-TUR-200",
    category: "Staples & Spices",
    unit: "Packets",
    mrp: 62,
    retailerPrice: 49,
    warehouseStock: 52,
    reservedStock: 0,
    lowStockThreshold: 15,
  },
  {
    id: "prod-8",
    name: "Toothpaste 150g",
    sku: "DENT-150",
    category: "Personal Care",
    unit: "Tubes",
    mrp: 95,
    retailerPrice: 79,
    warehouseStock: 38,
    reservedStock: 0,
    lowStockThreshold: 10,
  },
  {
    id: "prod-9",
    name: "Instant Noodles Pack (Pack of 12)",
    sku: "NOOD-12P",
    category: "Snacks & Instant Food",
    unit: "Packs",
    mrp: 168,
    retailerPrice: 138,
    warehouseStock: 42,
    reservedStock: 0,
    lowStockThreshold: 12,
  },
  {
    id: "prod-10",
    name: "Dishwash Bar (Pack of 3)",
    sku: "DISH-3P",
    category: "Home Care",
    unit: "Packs",
    mrp: 45,
    retailerPrice: 36,
    warehouseStock: 70,
    reservedStock: 0,
    lowStockThreshold: 20,
  },
];

export const INITIAL_RETAILERS: Retailer[] = [
  {
    id: "ret-1",
    name: "Sharma General Store",
    ownerName: "Mohan Sharma",
    phone: "+91 98292 41101",
    address: "Shop 14, Main Market, Sector 9",
    area: "Sector 9, Mansarovar",
    beatCode: "BEAT-04",
    pendingAmount: 3250,
    overdueAmount: 0,
    creditLimit: 20000,
    lastOrderDate: "2026-09-10",
    accountStatus: "Active",
    visitStatus: "Pending",
    visitSequence: 1,
    locationCoords: { lat: 26.8532, lng: 75.7615 },
  },
  {
    id: "ret-2",
    name: "Gupta Provision Store",
    ownerName: "Rajesh Gupta",
    phone: "+91 94140 88219",
    address: "Plot 82, Near City Park, Madhyam Marg",
    area: "Madhyam Marg, Mansarovar",
    beatCode: "BEAT-04",
    pendingAmount: 0,
    overdueAmount: 0,
    creditLimit: 15000,
    lastOrderDate: "2026-09-12",
    accountStatus: "Active",
    visitStatus: "Visited",
    visitSequence: 2,
    locationCoords: { lat: 26.8558, lng: 75.7672 },
  },
  {
    id: "ret-3",
    name: "Balaji Kirana Store",
    ownerName: "Sunil Agarwal",
    phone: "+91 97851 12093",
    address: "Corner Building, Opp Metro Pillar 44",
    area: "New Sanganer Road",
    beatCode: "BEAT-04",
    pendingAmount: 7800,
    overdueAmount: 7800,
    creditLimit: 25000,
    lastOrderDate: "2026-08-28",
    accountStatus: "Credit Blocked",
    visitStatus: "Visited",
    visitSequence: 3,
    locationCoords: { lat: 26.8624, lng: 75.7538 },
  },
  {
    id: "ret-4",
    name: "Pink City Super Mart",
    ownerName: "Vikram Singh",
    phone: "+91 98295 77610",
    address: "Shop 4, Commercial Complex, Shipra Path",
    area: "Shipra Path, Mansarovar",
    beatCode: "BEAT-04",
    pendingAmount: 12400,
    overdueAmount: 0,
    creditLimit: 30000,
    lastOrderDate: "2026-09-11",
    accountStatus: "Active",
    visitStatus: "Pending",
    visitSequence: 4,
    locationCoords: { lat: 26.8589, lng: 75.7725 },
  },
  {
    id: "ret-5",
    name: "Rajasthan General Store",
    ownerName: "Dinesh Verma",
    phone: "+91 94144 32900",
    address: "22, Main Circle, Patel Marg",
    area: "Patel Marg, Mansarovar",
    beatCode: "BEAT-04",
    pendingAmount: 1800,
    overdueAmount: 0,
    creditLimit: 18000,
    lastOrderDate: "2026-09-08",
    accountStatus: "Active",
    visitStatus: "Pending",
    visitSequence: 5,
    locationCoords: { lat: 26.8511, lng: 75.7694 },
  },
  {
    id: "ret-6",
    name: "Mahadev Departmental Store",
    ownerName: "Ramesh Choudhary",
    phone: "+91 98299 66341",
    address: "Showroom 1-B, Near VT Circle",
    area: "VT Road, Mansarovar",
    beatCode: "BEAT-04",
    pendingAmount: 5600,
    overdueAmount: 0,
    creditLimit: 22000,
    lastOrderDate: "2026-09-09",
    accountStatus: "Active",
    visitStatus: "Pending",
    visitSequence: 6,
    locationCoords: { lat: 26.8667, lng: 75.7601 },
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-seed-00482",
    orderNumber: "RF-2026-00482",
    retailerId: "ret-1",
    retailerName: "Sharma General Store",
    salespersonId: "emp-sales-1",
    salespersonName: "Rakesh Kumar",
    beatCode: "BEAT-04",
    beatName: "Mansarovar West",
    items: [
      {
        productId: "prod-1",
        productName: "Premium Tea 250g",
        sku: "TEA-250",
        quantity: 10,
        freeQuantity: 1, // Scheme Buy 10 get 1 free!
        unitPrice: 118,
        totalPrice: 1180,
      },
      {
        productId: "prod-2",
        productName: "Glucose Biscuit Box",
        sku: "BIS-BOX-24",
        quantity: 8,
        freeQuantity: 0,
        unitPrice: 205,
        totalPrice: 1640,
      },
      {
        productId: "prod-3",
        productName: "Mustard Oil 1L",
        sku: "OIL-1L",
        quantity: 4,
        freeQuantity: 0,
        unitPrice: 158,
        totalPrice: 649, // Adjusted with tax/freight to hit ₹3,469 exact total
      },
    ],
    totalAmount: 3469,
    paymentType: "Credit",
    status: "Submitted",
    statusTimeline: [
      {
        status: "Submitted",
        timestamp: "2026-09-13T09:45:00.000Z",
        updatedBy: "Rakesh Kumar (Salesperson)",
        notes: "Order booked during Mansarovar West beat visit.",
      },
    ],
    createdAt: "2026-09-13T09:45:00.000Z",
    updatedAt: "2026-09-13T09:45:00.000Z",
  },
  {
    id: "ord-seed-00481",
    orderNumber: "RF-2026-00481",
    retailerId: "ret-2",
    retailerName: "Gupta Provision Store",
    salespersonId: "emp-sales-1",
    salespersonName: "Rakesh Kumar",
    beatCode: "BEAT-04",
    beatName: "Mansarovar West",
    items: [
      {
        productId: "prod-4",
        productName: "Washing Powder 500g",
        sku: "DET-500",
        quantity: 15,
        freeQuantity: 0,
        unitPrice: 54,
        totalPrice: 810,
      },
      {
        productId: "prod-6",
        productName: "Salt 1kg",
        sku: "SALT-1K",
        quantity: 25,
        freeQuantity: 0,
        unitPrice: 22,
        totalPrice: 550,
      },
      {
        productId: "prod-9",
        productName: "Instant Noodles Pack (Pack of 12)",
        sku: "NOOD-12P",
        quantity: 10,
        freeQuantity: 0,
        unitPrice: 138,
        totalPrice: 1380,
      },
    ],
    totalAmount: 2740,
    paymentType: "UPI",
    status: "Delivered",
    statusTimeline: [
      {
        status: "Submitted",
        timestamp: "2026-09-12T10:15:00.000Z",
        updatedBy: "Rakesh Kumar",
      },
      {
        status: "Approved",
        timestamp: "2026-09-12T11:00:00.000Z",
        updatedBy: "Amit Agarwal",
      },
      {
        status: "Packed",
        timestamp: "2026-09-12T14:20:00.000Z",
        updatedBy: "Manoj Sharma",
      },
      {
        status: "Delivered",
        timestamp: "2026-09-12T17:30:00.000Z",
        updatedBy: "Suresh Yadav",
        notes: "UPI payment received ₹2,740 at shop.",
      },
    ],
    packageCount: 2,
    assignedDeliveryExecutive: "Suresh Yadav",
    createdAt: "2026-09-12T10:15:00.000Z",
    updatedAt: "2026-09-12T17:30:00.000Z",
  },
  {
    id: "ord-seed-00480",
    orderNumber: "RF-2026-00480",
    retailerId: "ret-4",
    retailerName: "Pink City Super Mart",
    salespersonId: "emp-sales-1",
    salespersonName: "Rakesh Kumar",
    beatCode: "BEAT-04",
    beatName: "Mansarovar West",
    items: [
      {
        productId: "prod-5",
        productName: "Bath Soap 100g (Pack of 4)",
        sku: "SOAP-4P",
        quantity: 12,
        freeQuantity: 0,
        unitPrice: 98,
        totalPrice: 1176,
      },
      {
        productId: "prod-8",
        productName: "Toothpaste 150g",
        sku: "DENT-150",
        quantity: 10,
        freeQuantity: 0,
        unitPrice: 79,
        totalPrice: 790,
      },
      {
        productId: "prod-10",
        productName: "Dishwash Bar (Pack of 3)",
        sku: "DISH-3P",
        quantity: 15,
        freeQuantity: 0,
        unitPrice: 36,
        totalPrice: 540,
      },
    ],
    totalAmount: 2506,
    paymentType: "Credit",
    status: "Delivered",
    statusTimeline: [
      {
        status: "Submitted",
        timestamp: "2026-09-11T11:00:00.000Z",
        updatedBy: "Rakesh Kumar",
      },
      {
        status: "Approved",
        timestamp: "2026-09-11T12:30:00.000Z",
        updatedBy: "Amit Agarwal",
      },
      {
        status: "Delivered",
        timestamp: "2026-09-11T18:00:00.000Z",
        updatedBy: "Suresh Yadav",
      },
    ],
    packageCount: 2,
    assignedDeliveryExecutive: "Suresh Yadav",
    createdAt: "2026-09-11T11:00:00.000Z",
    updatedAt: "2026-09-11T18:00:00.000Z",
  },
];

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: "del-seed-01",
    orderId: "ord-seed-00481",
    orderNumber: "RF-2026-00481",
    retailerId: "ret-2",
    retailerName: "Gupta Provision Store",
    address: "Plot 82, Near City Park, Madhyam Marg",
    area: "Madhyam Marg, Mansarovar",
    phone: "+91 94140 88219",
    packageCount: 2,
    amountToCollect: 0,
    paymentType: "UPI",
    status: "Delivered",
    assignedTo: "Suresh Yadav",
    deliveredAt: "2026-09-12T17:30:00.000Z",
    proofType: "OTP",
    otpUsed: "7142",
    sequenceNumber: 1,
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: "pay-1",
    receiptNumber: "RCP-2026-0104",
    retailerId: "ret-2",
    retailerName: "Gupta Provision Store",
    amount: 3500,
    paymentMethod: "UPI",
    referenceNumber: "UPI/3829104820",
    collectedBy: "Rakesh Kumar",
    collectedAt: "2026-09-13T10:30:00.000Z",
  },
  {
    id: "pay-2",
    receiptNumber: "RCP-2026-0103",
    retailerId: "ret-5",
    retailerName: "Rajasthan General Store",
    amount: 2500,
    paymentMethod: "Cash",
    referenceNumber: "CASH-REC-082",
    collectedBy: "Rakesh Kumar",
    collectedAt: "2026-09-13T11:15:00.000Z",
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: "emp-owner-1",
    name: "Amit Agarwal",
    role: "owner",
    title: "Proprietor & Director",
    phone: "+91 98290 12345",
    assignedRoute: "Overall Operations - Jaipur HQ",
    attendanceStatus: "Present",
    targetProgress: 88,
    estimatedIncentive: 0,
    approvedIncentive: 0,
    isActive: true,
  },
  {
    id: "emp-sales-1",
    name: "Rakesh Kumar",
    role: "salesperson",
    title: "Senior Field Sales Officer",
    phone: "+91 94140 54321",
    assignedRoute: "Mansarovar West (BEAT-04)",
    attendanceStatus: "On Field",
    targetProgress: 68,
    estimatedIncentive: 14500,
    approvedIncentive: 11200,
    isActive: true,
  },
  {
    id: "emp-wh-1",
    name: "Manoj Sharma",
    role: "warehouse",
    title: "Warehouse Operations Lead",
    phone: "+91 97850 67890",
    assignedRoute: "Jaipur Main Warehouse",
    attendanceStatus: "Warehouse",
    targetProgress: 79,
    estimatedIncentive: 8200,
    approvedIncentive: 6500,
    isActive: true,
  },
  {
    id: "emp-del-1",
    name: "Suresh Yadav",
    role: "delivery",
    title: "Senior Logistics Executive",
    phone: "+91 98291 98765",
    assignedRoute: "Mansarovar & Sanganer Corridor",
    attendanceStatus: "On Field",
    targetProgress: 76,
    estimatedIncentive: 7400,
    approvedIncentive: 5800,
    isActive: true,
  },
];

export const INITIAL_TARGETS: Target[] = [
  // Salesperson targets
  {
    id: "tar-sales-1",
    employeeId: "emp-sales-1",
    employeeName: "Rakesh Kumar",
    role: "salesperson",
    metricName: "Monthly Sales Target",
    targetValue: 500000,
    currentValue: 340000,
    unit: "₹",
    month: "September 2026",
    incentiveRate: "2.5% on achievement above 80%",
    estimatedIncentive: 8500,
    approvedIncentive: 7000,
  },
  {
    id: "tar-sales-2",
    employeeId: "emp-sales-1",
    employeeName: "Rakesh Kumar",
    role: "salesperson",
    metricName: "Productive Visits",
    targetValue: 150,
    currentValue: 108,
    unit: "Shops",
    month: "September 2026",
    incentiveRate: "₹30 per productive visit over 100",
    estimatedIncentive: 240,
    approvedIncentive: 200,
  },
  {
    id: "tar-sales-3",
    employeeId: "emp-sales-1",
    employeeName: "Rakesh Kumar",
    role: "salesperson",
    metricName: "Payment Collections",
    targetValue: 200000,
    currentValue: 145000,
    unit: "₹",
    month: "September 2026",
    incentiveRate: "1.0% on timely collection",
    estimatedIncentive: 1450,
    approvedIncentive: 1200,
  },
  {
    id: "tar-sales-4",
    employeeId: "emp-sales-1",
    employeeName: "Rakesh Kumar",
    role: "salesperson",
    metricName: "New Retailer Onboarding",
    targetValue: 10,
    currentValue: 6,
    unit: "Retailers",
    month: "September 2026",
    incentiveRate: "₹500 per activated account",
    estimatedIncentive: 3000,
    approvedIncentive: 2500,
  },

  // Warehouse targets
  {
    id: "tar-wh-1",
    employeeId: "emp-wh-1",
    employeeName: "Manoj Sharma",
    role: "warehouse",
    metricName: "Orders Packed Target",
    targetValue: 300,
    currentValue: 238,
    unit: "Orders",
    month: "September 2026",
    incentiveRate: "₹25 per order above 200",
    estimatedIncentive: 950,
    approvedIncentive: 800,
  },
  {
    id: "tar-wh-2",
    employeeId: "emp-wh-1",
    employeeName: "Manoj Sharma",
    role: "warehouse",
    metricName: "Picking Accuracy",
    targetValue: 98.5,
    currentValue: 98.5,
    unit: "%",
    month: "September 2026",
    incentiveRate: "₹4,000 monthly bonus for >=98%",
    estimatedIncentive: 4000,
    approvedIncentive: 4000,
  },
  {
    id: "tar-wh-3",
    employeeId: "emp-wh-1",
    employeeName: "Manoj Sharma",
    role: "warehouse",
    metricName: "On-Time Dispatch Rate",
    targetValue: 95,
    currentValue: 94,
    unit: "%",
    month: "September 2026",
    incentiveRate: "₹3,000 bonus for >=95%",
    estimatedIncentive: 2500,
    approvedIncentive: 2000,
  },

  // Delivery Executive targets
  {
    id: "tar-del-1",
    employeeId: "emp-del-1",
    employeeName: "Suresh Yadav",
    role: "delivery",
    metricName: "Delivery Target",
    targetValue: 240,
    currentValue: 184,
    unit: "Deliveries",
    month: "September 2026",
    incentiveRate: "₹30 per delivery above 150",
    estimatedIncentive: 1020,
    approvedIncentive: 900,
  },
  {
    id: "tar-del-2",
    employeeId: "emp-del-1",
    employeeName: "Suresh Yadav",
    role: "delivery",
    metricName: "Successful Delivery Rate",
    targetValue: 95,
    currentValue: 96,
    unit: "%",
    month: "September 2026",
    incentiveRate: "₹3,500 bonus for >=95%",
    estimatedIncentive: 3500,
    approvedIncentive: 3000,
  },
  {
    id: "tar-del-3",
    employeeId: "emp-del-1",
    employeeName: "Suresh Yadav",
    role: "delivery",
    metricName: "On-Field Collection Target",
    targetValue: 300000,
    currentValue: 235000,
    unit: "₹",
    month: "September 2026",
    incentiveRate: "1.2% on verified collections",
    estimatedIncentive: 2820,
    approvedIncentive: 2400,
  },
];

export const INITIAL_ACTIVITY: ActivityItem[] = [
  {
    id: "act-1",
    timestamp: "2026-09-13T09:45:00.000Z",
    role: "salesperson",
    userName: "Rakesh Kumar",
    action: "Order Booked",
    details: "Booked order RF-2026-00482 for Sharma General Store (₹3,469).",
    entityId: "ord-seed-00482",
  },
  {
    id: "act-2",
    timestamp: "2026-09-13T10:30:00.000Z",
    role: "salesperson",
    userName: "Rakesh Kumar",
    action: "Payment Collected",
    details: "Collected ₹3,500 via UPI from Gupta Provision Store.",
    entityId: "pay-1",
  },
  {
    id: "act-3",
    timestamp: "2026-09-13T11:15:00.000Z",
    role: "salesperson",
    userName: "Rakesh Kumar",
    action: "Payment Collected",
    details: "Collected ₹2,500 cash from Rajasthan General Store.",
    entityId: "pay-2",
  },
  {
    id: "act-4",
    timestamp: "2026-09-12T17:30:00.000Z",
    role: "delivery",
    userName: "Suresh Yadav",
    action: "Order Delivered",
    details: "Delivered RF-2026-00481 to Gupta Provision Store with OTP 7142.",
    entityId: "ord-seed-00481",
  },
];

export const INITIAL_ACTIVE_VISIT: ShopVisit = {
  id: "visit-active-sharma",
  retailerId: "ret-1",
  retailerName: "Sharma General Store",
  salespersonId: "emp-sales-1",
  startTime: "2026-09-13T09:30:00.000Z",
  durationMinutes: 28,
  isLocationVerified: true,
  stockAudits: [
    {
      productId: "prod-1",
      productName: "Premium Tea 250g",
      packSize: "250g Pouch",
      shopStock: 3,
      suggestedQty: 10,
      orderQty: 10,
    },
    {
      productId: "prod-2",
      productName: "Glucose Biscuit Box",
      packSize: "Box of 24",
      shopStock: 2,
      suggestedQty: 8,
      orderQty: 8,
    },
    {
      productId: "prod-3",
      productName: "Mustard Oil 1L",
      packSize: "1L Pet Bottle",
      shopStock: 1,
      suggestedQty: 5,
      orderQty: 4,
    },
    {
      productId: "prod-4",
      productName: "Washing Powder 500g",
      packSize: "500g Pack",
      shopStock: 6,
      suggestedQty: 0,
      orderQty: 0,
    },
  ],
  notes: "Shopkeeper requested prompt delivery by 4 PM today.",
  completed: false,
};

export const SEED_DATA_VERSION = "routeflow_v2.0_jaipur";
